### ISSUE TITLE
Doesn't work inside a php class

### ISSUE THREAD

**Issue by CaptainQuirk** [frioux/vim-lost#1]
Hi there,

When doing `gL` inside a php `function` inside a `class`, I get the class declaration as context, not the function I'm in.

Wouldn't it be practical to use the **ftplugin** mechanism to set the `regexp` used for looking for the context ?

Exposing a variable that can be set by the user to define this regexp language wise would also be great !

Thanks for your work !

**Comment by frioux** [comment]
Yeah let me look into doing just that.  I'll leave this open till I have a solution and you can test it.

**Comment by frioux** [comment]
Ok I added a feature to support this. I don't know PHP, but for JavaScript you could try:

``` viml
augroup vimrc
  autocmd!

  au FileType javascript let b:lost_regex = '\v\s*function'
augroup END
```
