### ISSUE TITLE
Fortran support.

### ISSUE THREAD

**Issue by fpnick** [frioux/vim-lost#3]
Really nice idea. Especially if - like in my case - your airline is so cluttered you usually don't see the subroutine information any more ;)

However there does not seem to be any Fortran support yet. Is that correct?

**Comment by frioux** [comment]
Fortran is one of the languages that doesn't work out of the box; you can configure it using these docs: https://github.com/frioux/vim-lost/blob/master/doc/lost.txt#L35-L45.  Let me know if that's not clear.

Thanks!
